title: raspy-windbird
logo: /assets/img/icon.jpg
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-clean-blog
# social_links:
#   - { platform: x, user_rul: "https://x.com/comimome"}
